// Code generated by ent, DO NOT EDIT.

package ent

import (
	"poll_app/ent/notification"
	"poll_app/ent/poll"
	"poll_app/ent/polloption"
	"poll_app/ent/schema"
	"poll_app/ent/user"
	"poll_app/ent/vote"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	notificationFields := schema.Notification{}.Fields()
	_ = notificationFields
	// notificationDescMessage is the schema descriptor for message field.
	notificationDescMessage := notificationFields[0].Descriptor()
	// notification.MessageValidator is a validator for the "message" field. It is called by the builders before save.
	notification.MessageValidator = notificationDescMessage.Validators[0].(func(string) error)
	// notificationDescType is the schema descriptor for type field.
	notificationDescType := notificationFields[1].Descriptor()
	// notification.DefaultType holds the default value on creation for the type field.
	notification.DefaultType = notificationDescType.Default.(string)
	// notificationDescRead is the schema descriptor for read field.
	notificationDescRead := notificationFields[3].Descriptor()
	// notification.DefaultRead holds the default value on creation for the read field.
	notification.DefaultRead = notificationDescRead.Default.(bool)
	// notificationDescCreatedAt is the schema descriptor for created_at field.
	notificationDescCreatedAt := notificationFields[4].Descriptor()
	// notification.DefaultCreatedAt holds the default value on creation for the created_at field.
	notification.DefaultCreatedAt = notificationDescCreatedAt.Default.(func() time.Time)
	pollFields := schema.Poll{}.Fields()
	_ = pollFields
	// pollDescTitle is the schema descriptor for title field.
	pollDescTitle := pollFields[0].Descriptor()
	// poll.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	poll.TitleValidator = pollDescTitle.Validators[0].(func(string) error)
	// pollDescCreatedAt is the schema descriptor for created_at field.
	pollDescCreatedAt := pollFields[2].Descriptor()
	// poll.DefaultCreatedAt holds the default value on creation for the created_at field.
	poll.DefaultCreatedAt = pollDescCreatedAt.Default.(func() time.Time)
	// pollDescUpdatedAt is the schema descriptor for updated_at field.
	pollDescUpdatedAt := pollFields[3].Descriptor()
	// poll.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	poll.DefaultUpdatedAt = pollDescUpdatedAt.Default.(func() time.Time)
	// poll.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	poll.UpdateDefaultUpdatedAt = pollDescUpdatedAt.UpdateDefault.(func() time.Time)
	polloptionFields := schema.PollOption{}.Fields()
	_ = polloptionFields
	// polloptionDescText is the schema descriptor for text field.
	polloptionDescText := polloptionFields[0].Descriptor()
	// polloption.TextValidator is a validator for the "text" field. It is called by the builders before save.
	polloption.TextValidator = polloptionDescText.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	voteFields := schema.Vote{}.Fields()
	_ = voteFields
	// voteDescCreatedAt is the schema descriptor for created_at field.
	voteDescCreatedAt := voteFields[0].Descriptor()
	// vote.DefaultCreatedAt holds the default value on creation for the created_at field.
	vote.DefaultCreatedAt = voteDescCreatedAt.Default.(func() time.Time)
}
